# swagger.yaml

openapi: 3.0.0
info:
  title: API Dokumentation
  version: 1.0.0
paths:
  /useraccounts:
    get:
      summary: Gibt alle Benutzerkonten zurück.
      responses:
        200:
          description: Erfolgreiche Anfrage. Gibt eine Liste der Benutzerkonten zurück.
    post:
      summary: Fügt ein neues Benutzerkonto hinzu.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                first_name:
                  type: string
                last_name:
                  type: string
                phone_number:
                  type: string
                created_at:
                  type: string
                  format: date-time
              required:
                - username
                - email
                - password
                - first_name
                - last_name
                - phone_number
                - created_at
      responses:
        200:
          description: Erfolgreiche Anfrage. Gibt das hinzugefügte Benutzerkonto zurück.
